apiVersion: v2
name: influxdb3-core
description: A Helm chart for deploying InfluxDB 3 Core on Kubernetes
type: application
version: 0.2.0
appVersion: "3.9.3"
keywords:
  - influxdb
  - time-series
  - database
  - metrics
  - iot
  - open-source
home: https://www.influxdata.com/products/influxdb/
sources:
  - https://github.com/influxdata/influxdb
  - https://docs.influxdata.com/influxdb3/core/
maintainers:
  - name: NigelVanHattum
icon: https://www.influxdata.com/wp-content/uploads/influxdata-logo.svg
