{{/*
Deploy Kasm API Service .Values.components.api service definition
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $constants.api.svc }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $constants.api.name }}-svc
    app.kubernetes.io/component: {{ $constants.api.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
    {{- with .Values.components.api.labels }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.extraLabels.service }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- with .Values.annotations.service }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ $constants.api.name }}
  ports:
    - name: {{ printf "%s-svc-%s" $constants.api.name ($constants.api.port | toString) }}
      protocol: TCP
      port: {{ $constants.api.port }}