{{/*
Initialize the DB
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- $kasmSecrets := (.Values.dbManagement.upgrade.oldDbSecretsName | default (printf "%s-secrets" .Release.Name)) }}
{{- if .Values.dbManagement.backupCron.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ .Values.dbManagement.backupCron.pvcName | default (printf "%s-db-backup-pvc" .Release.Name) }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ .Release.Name }}-db-backup
    app.kubernetes.io/component: db-backup
    {{- include "kasm.defaultLabels" . | indent 4 }}
    {{- with .Values.extraLabels.pvc }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- with .Values.annotations.pvc }}
  annotations: {{- toYaml . | nindent 4 }}
    helm.sh/resource-policy: keep
  {{- end }}
spec:
  {{- with .Values.dbManagement.backupCron.storageClass }}
  storageClassName: {{ . }}
  {{- end }}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.dbManagement.backupCron.pvcSize | default "5Gi" }}
{{- end }}