{{/*
Deploy Kasm API Service .Values.database service definition
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- if eq .Values.database.standalone false }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $constants.db.svc }}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $constants.db.svc }}-svc
    app.kubernetes.io/component: {{ $constants.db.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
    {{- with .Values.database.labels }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.extraLabels.service }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- with .Values.annotations.service }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  clusterIP: None
  selector:
    app.kubernetes.io/name: {{ $constants.db.name }}
  ports:
    - name: {{ printf "%s-svc-%s" $constants.db.svc ($constants.db.port | toString) }}
      protocol: TCP
      port: {{ $constants.db.port }}
{{- end }}