{{/*
Deploy the Kasm Proxy service
*/}}
{{- if and (or .Values.ingress.enabled .Values.route.enabled) (eq .Values.proxyService.type "LoadBalancer") -}}
  {{- fail "The service.type must not be LoadBalancer when using an ingress or a route - any load balancer or Route should be provisioned using the Ingress/Route settings. Set service.type=ClusterIP or mark ingress.enabled or route.enabled to disabled." -}}
{{- end -}}
{{- if and (eq .Values.proxyService.type "LoadBalancer") .Values.kasmZones -}}
  {{- fail "The service.type must not be LoadBalancer when using a Multi-Zone Kasm deployment - any load balancer or Route should be provisioned using the Ingress/Route settings. Set service.type=ClusterIP or remove your kasmZones settings." -}}
{{- end -}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- if eq .Values.proxyService.type "LoadBalancer" -}}
apiVersion: v1
kind: Service
metadata:
  name: {{ $constants.proxy.svc }}-ext
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $constants.proxy.svc }}-ext-svc
    app.kubernetes.io/component: {{ $constants.proxy.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
    {{- with .Values.components.proxy.labels }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.extraLabels.service }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- if or .Values.proxyService.annotations .Values.annotations.service }}
  annotations:
    {{- with .Values.proxyService.annotations }}{{ toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.annotations.service }}{{ toYaml . | nindent 4 }}{{- end }}
  {{- end }}
spec:
  type: {{ .Values.proxyService.type }}
  selector:
    app.kubernetes.io/name: {{ $constants.proxy.name }}-default
  ports:
    - name: {{ printf "%s-ext-svc-%s" $constants.proxy.svc ($constants.proxy.extHttps | toString) }}
      protocol: TCP
      port: {{ $constants.proxy.extHttps }}
      targetPort: {{ $constants.proxy.portName }}-https
{{- end }}