{{/*
Deploy the RDP Gateway if .Values.components.rdpGateway.enabled set to true
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- $rdpPort := 3389 -}}
{{- if .Values.components.rdpGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $constants.rdpGateway.svc }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $constants.rdpGateway.svc }}-svc
    app.kubernetes.io/component: {{ $constants.rdpGateway.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
    {{- with $.Values.components.rdpGateway.labels }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $.Values.extraLabels.service }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $.Values.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- with $.Values.annotations.service }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ $constants.rdpGateway.name }}
  ports:
    - name: {{ printf "%s-svc-%s" $constants.rdpGateway.svc ($constants.rdpGateway.port | toString) }}
      protocol: TCP
      port: {{ $constants.rdpGateway.port }}
    - name: {{ printf "%s-svc-%s" $constants.rdpGateway.svc ($rdpPort | toString) }}
      protocol: TCP
      port: {{ $rdpPort }}
{{- end }}