{{/*
Deploy the Redis if .Values.components.rdpHttpsGateway.enabled set to true
*/}}
{{- $constants := (include "kasm.constants" . | fromYaml) -}}
{{- if .Values.components.rdpHttpsGateway.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ $constants.rdpHttpsGateway.svc }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/name: {{ $constants.rdpHttpsGateway.svc }}-svc
    app.kubernetes.io/component: {{ $constants.rdpHttpsGateway.component }}
    {{- include "kasm.defaultLabels" . | indent 4 }}
    {{- with $.Values.components.rdpHttpsGateway.labels }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $.Values.extraLabels.service }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with $.Values.labels }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- with $.Values.annotations.service }}
  annotations: {{ toYaml . | nindent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ $constants.rdpHttpsGateway.name }}
  ports:
    - name: {{ printf "%s-svc-%s" $constants.rdpHttpsGateway.svc ($constants.rdpHttpsGateway.port | toString) }}
      protocol: TCP
      port: {{ $constants.rdpHttpsGateway.port }}
{{- end }}