apiVersion: v1
kind: Service
metadata:
  name: {{ include "paperless-ngx.fullname" . }}-redis
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "paperless-ngx.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: redis