apiVersion: v1
kind: Secret
metadata:
  name: {{ include "paperless-ngx.fullname" . }}
  labels:
    {{- include "paperless-ngx.labels" . | nindent 4 }}
type: Opaque
data:
  admin-password: {{ .Values.paperless.env.PAPERLESS_ADMIN_PASSWORD | b64enc | quote }}
  secret-key: {{ .Values.paperless.env.PAPERLESS_SECRET_KEY | b64enc | quote }}
{{- if not .Values.paperless.database.enabled }}
  db-password: {{ .Values.paperless.database.password | b64enc | quote }}
{{- end }}
{{- if .Values.paperless.authentik.enabled }}
  authentik-client-secret: {{ .Values.paperless.authentik.clientSecret | b64enc | quote }}
{{- end }}