apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdarr.fullname" . }}-server
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.server.type }}
  ports:
    - port: {{ .Values.service.server.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "tdarr.selectorLabels" . | nindent 4 }}
