apiVersion: v1
kind: Service
metadata:
  name: {{ include "tdarr.fullname" . }}-webui
  labels:
    {{- include "tdarr.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.webUI.type }}
  ports:
    - port: {{ .Values.service.webUI.port }}
      targetPort: {{ .Values.service.webUI.port }}
      protocol: TCP
      name: http
  selector:
    {{- include "tdarr.selectorLabels" . | nindent 4 }}
