{{- if not .Values.floatplane.credentials.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: floatplane-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "floatplane-downloader.labels" . | nindent 4 }}
data:
  plex-token: {{b64enc ( trim ( quote .Values.floatplane.credentials.plexToken ) )}}
{{- end }}