{{- if not .Values.floatplane.credentials.useExistingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: floatplane-credentials
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "floatplane-downloader.labels" . | nindent 4 }}
data:
  username: {{b64enc (required "Please provide the floatplane username" .Values.floatplane.credentials.username | trim)}}
  password: {{b64enc (required "Please provide the floatplane password" .Values.floatplane.credentials.password | trim)}}
  mfa: {{b64enc ( trim ( quote .Values.floatplane.credentials.mfa ) )}}
  plex-token: {{b64enc ( trim ( quote .Values.floatplane.credentials.plexToken ) )}}
{{- end }}