name: Release KASM Chart
on:
  schedule:
    - cron: '0 0 1 * *'  # Runs monthly on the 1st at 00:00 UTC. Adjust as needed (e.g., '0 0 15 * *' for the 15th).
  workflow_dispatch:

jobs:
  release:
    # depending on default permission settings for your org (contents being read-only or read-write for workloads), you will have to add permissions
    # see: https://docs.github.com/en/actions/security-guides/automatic-token-authentication#modifying-the-permissions-for-the-github_token
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          repository: NigelVanHattum/Homelab-Helm-charts

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Run Helm Chart Releaser
        uses: NigelVanHattum/chart-releaser-action@v0.81 
        with:
          source: kasmtech/kasm-helm
          target: NigelVanHattum/Homelab-Helm-charts
          charts_dir: .
          skip_existing: false  
          mark_as_latest: true  # Mark as latest release
        env:
          CR_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
